version: "3"
services:

  opspi:
    container_name: opspi
    image: "${APP_IMAGE}"
    env_file: .env
    ports:
      - '3000:3000'
    volumes:
      - /var/log/opspi/:/project/log/
    command: bundle exec rails server -b 0.0.0.0
    restart: unless-stopped
  sidekiq:
    container_name: sidekiq
    image: "${APP_IMAGE}"
    env_file: .env
    #volumes:
    #  - .:/myapp
    links:
      - opspi
    command: bundle exec sidekiq
