version: "3"
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /etc/nginx/certs
      - /etc/nginx/vhost.d
      - /usr/share/nginx/html

  nginx-proxy-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    environment:
      - DEFAULT_EMAIL=naveen.tiwari@stackexpress.com
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/acme.sh
        #volumes_from:
        #- nginx-proxy

  opspi:
    container_name: opspi
    image: "${APP_IMAGE}"
    env_file: .env
    ports:
      - '3000:3000'
    volumes:
      - /var/log/opspi/:/project/log/
    command: bash -c "rake db:migrate && bin/rails server --port 3000 --binding 0.0.0.0"
    restart: unless-stopped
  cron:
    container_name: opspi_cron
    image: "${APP_IMAGE}"
    env_file: .env
    #volumes:
    #  - .:/myapp
    links:
      - opspi
    command: bash -c "RAILS_ENV=production whenever --update-crontab"
  sidekiq:
    container_name: sidekiq
    image: "${APP_IMAGE}"
    env_file: .env
    #volumes:
    #  - .:/myapp
    links:
      - opspi
    command: bundle exec sidekiq
