version: "3"
services:

  opspi:
    container_name: opspi-stag
    image: "${APP_IMAGE}"
    #image: registry.gitlab.com/stackexpresso/opspi2020/opspi-rails:b8851674
    env_file: .env
    ports:
      - '4000:3000'
    volumes:
      - /var/log/opspi-stagging/:/project/log/
    command: bash -c "rake db:migrate && bin/rails server --port 3000 --binding 0.0.0.0"
    restart: unless-stopped
