version: "3"
services:
  opspi:
    container_name: opspi
    image: "${APP_IMAGE}"
    env_file: .env
    ports:
      - '3000:3000'
    volumes:
      - /var/log/opspi/:/project/log/
      - "${DATA_DIR}/config/reseller_api_enc_private.pem:/project/config/reseller_api_enc_private.pem"
      - "${DATA_DIR}/config/reseller_api_enc_public.pem:/project/config/reseller_api_enc_public.pem"
    restart: unless-stopped
  cron:
    container_name: opspi-cron
    image: "${APP_IMAGE}"
    env_file: .env
    command: bash -c "bundle exec whenever --update-crontab && cron -f -L 15"

  sidekiq:
    container_name: sidekiq
    image: "${APP_IMAGE}"
    env_file: .env
    #volumes:
    #  - .:/myapp
    links:
      - opspi
    command: bundle exec sidekiq
