version: "3"
services:

  opspi:
    container_name: opspi
    image: "${APP_IMAGE}"
    args:
      - RAILS_ENV
      - DB_HOST
      - DB_NAME
      - DB_USERNAME
      - DB_PASSWORD
      - DB_PORT
      - SECRET_KEY_BASE
    env_file: .env
    ports:
      - '3000:3000'
    volumes:
      - /var/log/opspi/:/project/log/
    command: bash -c "bin/rails server --port 3000 --binding 0.0.0.0"
    restart: unless-stopped
  sidekiq:
    container_name: sidekiq
    image: "${APP_IMAGE}"
    env_file: .env
    #volumes:
    #  - .:/myapp
    links:
      - opspi
    command: bundle exec sidekiq
