api_url: <%=ENV["CHATWOOT_API_URL"]%>
api_version: <%=ENV["API_VERSION"]%>
api_access_token: <%=ENV["CHATWOOT_USER_API_KEY"]%>
account_id: <%=ENV["CHATWOOT_ACCOUNT_ID"]%>
platform_api_key: <%=ENV["CHATWOOT_PLATFORM_API_KEY"]%>