default: &default
  database: <%= ENV['DB_NAME'] %>
  adapter: <%= ENV['DB_ADAPTER'] ||= 'mysql2' %> 
  encoding: utf8mb4
  pool: 5
  host: <%= ENV['DB_HOST'] %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  port: <%= ENV['DB_PORT'] %>
  reconnect: true

development:
  <<: *default

test:
  <<: *default
  database: <%= ENV['TEST_DB_NAME'] %>

production:
  <<: *default

staging:
  <<: *default
qa:
  <<: *default
  