development:
  base_url: https://173.0.137.83:8080/remote/
  user_url: https://173.0.137.83:8080/
  username: <%= ENV["ISP_CONFIG_USERNAME"]%>
  password: <%= ENV["ISP_CONFIG_PASSWORD"]%>
  timeout: 30
  log: true
  register_users: true

staging:
  base_url: https://173.0.137.83:8080/remote/
  user_url: https://173.0.137.83:8080/
  username: 
  password: 
  register_users: false

test:
  base_url: https://173.0.137.83:8080/remote/
  user_url: https://173.0.137.83:8080/
  username: 
  password: 
  register_users: false
  
production:
  base_url: https://173.0.137.83:8080/remote/
  user_url: https://173.0.137.83:8080/
  username: <%= ENV["ISP_CONFIG_USERNAME"]%>
  password: <%= ENV["ISP_CONFIG_PASSWORD"]%>
  timeout: 30
  log: false
  register_users: true
